# Cloud Build configuration for RAG Bidding API
# Triggered by Git repo push to deploy to Cloud Run
#
# Setup:
# 1. Connect GitHub repo to Cloud Build
# 2. Create trigger with this config file
# 3. Ensure Service Account has Secret Manager access

steps:
  # ===== Build Docker Image =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rag-bidding-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rag-bidding-api:latest'
      - '.'
    timeout: '1200s'  # 20 min timeout for build

  # ===== Push to Container Registry =====
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/rag-bidding-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/rag-bidding-api:latest'

  # ===== Deploy to Cloud Run =====
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rag-bidding-api'
      - '--image=gcr.io/$PROJECT_ID/rag-bidding-api:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300s'
      - '--concurrency=80'
      # Secrets from Secret Manager
      - '--set-secrets=DATABASE_PASSWORD=rag-bidding-db-password:latest'
      - '--set-secrets=GOOGLE_API_KEY=rag-bidding-google-api-key:latest'
      - '--set-secrets=JWT_SECRET_KEY=rag-bidding-jwt-secret:latest'
      - '--set-secrets=OAUTH_CLIENT_SECRET=rag-bidding-oauth-secret:latest'
      - '--set-secrets=OPENAI_API_KEY=rag-bidding-openai-key:latest'
      # Environment variables (non-sensitive)
      - '--set-env-vars=PYTHONUNBUFFERED=1'
      - '--set-env-vars=RERANKER_PROVIDER=vertex'
      - '--set-env-vars=ENABLE_REDIS_CACHE=true'
      - '--set-env-vars=RATE_LIMIT_ENABLED=true'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster build

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/rag-bidding-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/rag-bidding-api:latest'

timeout: '1800s'  # 30 min total timeout
