# Cloud Build configuration for RAG Bidding API
# Triggered by Git repo push to deploy to Cloud Run
#
# Prerequisites:
# 1. Connect GitHub repo to Cloud Build
# 2. Create secrets in Secret Manager (see DEPLOYMENT_GUIDE.md)
# 3. Grant Cloud Build SA access to Secret Manager
# 4. Create Cloud Build trigger

substitutions:
  _REGION: "asia-southeast1"
  _SERVICE_NAME: "rag-bidding-api"
  _CLOUD_SQL_INSTANCE_NAME: "rag-bid-db" # Just the instance name, project & region added automatically
  _GOOGLE_OAUTH_CLIENT_ID: "" # Set in Cloud Build trigger
  _FRONTEND_URL: "" # Set in Cloud Build trigger

steps:
  # ===== Build Docker Image =====
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"
      - "."
    timeout: "1200s"

  # ===== Push to Container Registry =====
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"]

  # ===== Deploy to Cloud Run =====
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=2Gi"
      - "--cpu=2"
      - "--min-instances=0"
      - "--max-instances=10"
      - "--timeout=300s"
      - "--concurrency=80"
      # Cloud SQL connection (format: project:region:instance)
      - "--add-cloudsql-instances=$PROJECT_ID:${_REGION}:${_CLOUD_SQL_INSTANCE_NAME}"
      # Secrets from Secret Manager
      - "--set-secrets=DATABASE_URL=rag-bidding-db-url:latest"
      - "--set-secrets=GOOGLE_API_KEY=rag-bidding-google-api-key:latest"
      - "--set-secrets=JWT_SECRET_KEY=rag-bidding-jwt-secret:latest"
      - "--set-secrets=GOOGLE_OAUTH_CLIENT_SECRET=rag-bidding-oauth-secret:latest"
      # ===== CRITICAL: Environment Mode (fixes "local database" bug) =====
      - "--set-env-vars=ENV_MODE=production"
      - "--set-env-vars=USE_CLOUD_DB=false"
      # Note: USE_CLOUD_DB=false because DATABASE_URL from Secret Manager is used directly
      # The code will use DATABASE_URL when provided, bypassing the cloud_db_host logic

      # Environment variables (non-sensitive)
      - "--set-env-vars=PYTHONUNBUFFERED=1"
      - "--set-env-vars=EMBED_PROVIDER=vertex"
      - "--set-env-vars=RERANKER_PROVIDER=vertex"
      - "--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "--set-env-vars=GOOGLE_CLOUD_LOCATION=${_REGION}"
      - "--set-env-vars=ENABLE_REDIS_CACHE=true"
      - "--set-env-vars=ENABLE_ANSWER_CACHE=true"
      - "--set-env-vars=ENABLE_SEMANTIC_CACHE=true"
      - "--set-env-vars=RATE_LIMIT_ENABLED=true"
      - "--set-env-vars=ENABLE_RERANKING=true"
      - "--set-env-vars=ENABLE_ADAPTIVE_RETRIEVAL=true"
      - "--set-env-vars=ENABLE_QUERY_ENHANCEMENT=true"
      - "--set-env-vars=RAG_MODE=balanced"
      - "--set-env-vars=USE_GCS_STORAGE=true"
      - "--set-env-vars=GCS_BUCKET=rag-bidding-documents"
      # OAuth Client ID (set via substitution in trigger)
      - "--set-env-vars=GOOGLE_OAUTH_CLIENT_ID=${_GOOGLE_OAUTH_CLIENT_ID}"
      # Frontend URL (set via substitution in trigger)
      - "--set-env-vars=FRONTEND_URL=${_FRONTEND_URL}"
      - "--set-env-vars=CORS_ORIGINS=${_FRONTEND_URL}"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"

timeout: "1800s"
