"""Initial schema with documents and embeddings

Revision ID: 0dd6951d6844
Revises: 
Create Date: 2025-11-27 16:44:54.161954+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd6951d6844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('documents', 'document_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique document identifier',
               existing_comment='Unique identifier following Vietnamese legal citation format',
               existing_nullable=False)
    op.alter_column('documents', 'document_name',
               existing_type=sa.TEXT(),
               comment='Document title/name',
               existing_nullable=False)
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='Category: legal, bidding, etc.',
               existing_comment='One of 7 categories mapping to data/raw folders',
               existing_nullable=False)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type: law, decree, circular, bidding_form, etc.',
               existing_nullable=False)
    op.alter_column('documents', 'source_file',
               existing_type=sa.TEXT(),
               comment='Path to source file',
               existing_nullable=False)
    op.alter_column('documents', 'file_name',
               existing_type=sa.TEXT(),
               comment='Original filename',
               existing_nullable=False)
    op.alter_column('documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               comment='Number of chunks/embeddings',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status: active, processing, expired, deleted',
               existing_comment='Document status for toggle functionality',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='Creation timestamp',
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='Last update timestamp',
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('documents_document_id_key'), 'documents', type_='unique')
    op.drop_index(op.f('idx_documents_category'), table_name='documents')
    op.drop_index(op.f('idx_documents_source'), table_name='documents')
    op.drop_index(op.f('idx_documents_status'), table_name='documents')
    op.drop_index(op.f('idx_documents_type'), table_name='documents')
    op.create_index('idx_documents_category_status', 'documents', ['category', 'status'], unique=False)
    op.create_index('idx_documents_status_type', 'documents', ['status', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_source_file'), 'documents', ['source_file'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table_comment(
        'documents',
        'Application-level document management table',
        existing_comment='Master table for all legal documents related to bidding',
        schema=None
    )
    op.alter_column('langchain_pg_collection', 'uuid',
               existing_type=sa.UUID(),
               comment='Collection UUID',
               existing_nullable=False)
    op.alter_column('langchain_pg_collection', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment="Collection name (e.g., 'docs')")
    op.alter_column('langchain_pg_collection', 'cmetadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Collection metadata',
               existing_nullable=True)
    op.drop_constraint(op.f('langchain_pg_collection_name_key'), 'langchain_pg_collection', type_='unique')
    op.create_index('langchain_pg_collection_name_key', 'langchain_pg_collection', ['name'], unique=True)
    op.create_table_comment(
        'langchain_pg_collection',
        'LangChain internal collection management - DO NOT modify directly',
        existing_comment=None,
        schema=None
    )
    op.alter_column('langchain_pg_embedding', 'id',
               existing_type=sa.VARCHAR(),
               comment='Chunk ID (UUID format)',
               existing_nullable=False)
    op.alter_column('langchain_pg_embedding', 'collection_id',
               existing_type=sa.UUID(),
               comment='Reference to collection',
               existing_nullable=True)
    op.alter_column('langchain_pg_embedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               comment='OpenAI text-embedding-3-large vector (3072-dim)',
               existing_nullable=True)
    op.alter_column('langchain_pg_embedding', 'document',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               comment='Chunk text content',
               existing_nullable=True)
    op.alter_column('langchain_pg_embedding', 'cmetadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Chunk metadata: document_id, chunk_index, hierarchy, etc.',
               existing_nullable=True)
    op.create_index('idx_embedding_document_type', 'langchain_pg_embedding', [sa.literal_column("(cmetadata ->> 'document_type')")], unique=False)
    op.create_table_comment(
        'langchain_pg_embedding',
        'Vector embeddings storage with metadata',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'langchain_pg_embedding',
        existing_comment='Vector embeddings storage with metadata',
        schema=None
    )
    op.drop_index('idx_embedding_document_type', table_name='langchain_pg_embedding')
    op.alter_column('langchain_pg_embedding', 'cmetadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Chunk metadata: document_id, chunk_index, hierarchy, etc.',
               existing_nullable=True)
    op.alter_column('langchain_pg_embedding', 'document',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               comment=None,
               existing_comment='Chunk text content',
               existing_nullable=True)
    op.alter_column('langchain_pg_embedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               comment=None,
               existing_comment='OpenAI text-embedding-3-large vector (3072-dim)',
               existing_nullable=True)
    op.alter_column('langchain_pg_embedding', 'collection_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Reference to collection',
               existing_nullable=True)
    op.alter_column('langchain_pg_embedding', 'id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Chunk ID (UUID format)',
               existing_nullable=False)
    op.drop_table_comment(
        'langchain_pg_collection',
        existing_comment='LangChain internal collection management - DO NOT modify directly',
        schema=None
    )
    op.drop_index('langchain_pg_collection_name_key', table_name='langchain_pg_collection')
    op.create_unique_constraint(op.f('langchain_pg_collection_name_key'), 'langchain_pg_collection', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('langchain_pg_collection', 'cmetadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Collection metadata',
               existing_nullable=True)
    op.alter_column('langchain_pg_collection', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment="Collection name (e.g., 'docs')")
    op.alter_column('langchain_pg_collection', 'uuid',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Collection UUID',
               existing_nullable=False)
    op.create_table_comment(
        'documents',
        'Master table for all legal documents related to bidding',
        existing_comment='Application-level document management table',
        schema=None
    )
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_file'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_index('idx_documents_status_type', table_name='documents')
    op.drop_index('idx_documents_category_status', table_name='documents')
    op.create_index(op.f('idx_documents_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('idx_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('idx_documents_source'), 'documents', ['source_file'], unique=False)
    op.create_index(op.f('idx_documents_category'), 'documents', ['category'], unique=False)
    op.create_unique_constraint(op.f('documents_document_id_key'), 'documents', ['document_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Last update timestamp',
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Creation timestamp',
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Document status for toggle functionality',
               existing_comment='Status: active, processing, expired, deleted',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of chunks/embeddings',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'file_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original filename',
               existing_nullable=False)
    op.alter_column('documents', 'source_file',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Path to source file',
               existing_nullable=False)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type: law, decree, circular, bidding_form, etc.',
               existing_nullable=False)
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='One of 7 categories mapping to data/raw folders',
               existing_comment='Category: legal, bidding, etc.',
               existing_nullable=False)
    op.alter_column('documents', 'document_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Document title/name',
               existing_nullable=False)
    op.alter_column('documents', 'document_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique identifier following Vietnamese legal citation format',
               existing_comment='Unique document identifier',
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
